version: '3'
services:
  zap:
      #dockerfile: Dockerfile
    image: nnedelchev/zap
      #ports:
      #- 8090:8090
    command: zap-api-scan.py -t https://petstore.swagger.io/v2/swagger.json -f openapi -r report.html
    volumes:
      - /tmp/report:/zap/wrk:rw

    #logging:
    #  driver: "none"
